server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wjc?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true
    password:
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filter: stat

mybatis:
  type-aliases-package: cn.gson.wangjunchi.model.pojos
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    cache-enabled: true